controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  # config/routes.yaml

app_logout:
  path: /logout
  controller: App\Controller\LoginController::logout
